#!/bin/sh

echo "mac pre-commit"

#if git rev-parse --verify HEAD >/dev/null 2>&1
#then
#	against=HEAD
#else
#	# Initial commit: diff against an empty tree object
#	against=$(git hash-object -t tree /dev/null)
#fi


# 获取提交的json配置文件
JSON_FILES=$(git diff --cached --name-only --diff-filter=ACM -- '*.json')
if test ${#JSON_FILES} -gt 0
then
	for FILE in $JSON_FILES
	do
		echo FILE
	done
	if [[ $SUCC == 0 ]]; then
		exit 1
	fi
fi